### ISSUE TITLE
Prevent API from creating API keys/secrets with the # sign

### ISSUE THREAD

**Issue by rheinardkorf** [wptide/wporg-tide-api#3]
When using the # symbol in .env files it gets treated as a comment marker. Thus authentication with the API fails.

It is not possible to escape the # in .env files so the best remedy would be to prevent them appearing in KV pairs at all.

**Comment by jeffpaul** [comment]
Issue moved to [wptide/wptide #146](https://github.com/wptide/wptide/issues/146) via [**ZenHub**](https://www.zenhub.com/)
